#!/usr/bin/env bash

set -euo pipefail

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_directory/.." && pwd)"
cd "$project_root"

usage() {
  printf 'Usage: %s vMAJOR.MINOR.PATCH [stable|prerelease]\n' "$0" >&2
}

release_tag="${1:-}"
release_channel="${2:-stable}"
semver_pattern='^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?$'

if [[ ! "$release_tag" =~ $semver_pattern ]]; then
  usage
  printf 'Error: release tag must be a valid semantic version beginning with v.\n' >&2
  exit 2
fi

case "$release_channel" in
  stable | prerelease) ;;
  *)
    usage
    printf 'Error: release channel must be stable or prerelease.\n' >&2
    exit 2
    ;;
esac

if [[ "$release_tag" == *-* && "$release_channel" != "prerelease" ]]; then
  printf 'Error: a tag with a prerelease suffix must use the prerelease channel.\n' >&2
  exit 2
fi

if [[ "$release_tag" != *-* && "$release_channel" == "prerelease" ]]; then
  printf 'Error: the prerelease channel requires a SemVer suffix such as -rc.1.\n' >&2
  exit 2
fi

for command_name in git gh; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf 'Error: required command is not installed: %s\n' "$command_name" >&2
    exit 1
  fi
done

if [[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]]; then
  printf 'Error: run this command from the Overseer Git repository.\n' >&2
  exit 1
fi

if ! git remote get-url origin >/dev/null 2>&1; then
  printf 'Error: the repository does not have an origin remote.\n' >&2
  exit 1
fi

printf 'Checking GitHub authentication...\n'
gh auth status >/dev/null

printf 'Fetching origin/main and release tags...\n'
git fetch origin main --tags

if git show-ref --verify --quiet "refs/tags/$release_tag"; then
  printf 'Error: tag %s already exists. Release tags must not be reused.\n' \
    "$release_tag" >&2
  exit 1
fi

release_commit="$(git rev-parse --verify origin/main)"
prerelease_args=()
if [[ "$release_channel" == "prerelease" ]]; then
  prerelease_args+=(--prerelease)
fi

printf '\nRelease summary\n'
printf '  Tag:     %s\n' "$release_tag"
printf '  Channel: %s\n' "$release_channel"
printf '  Target:  origin/main at %s\n' "$release_commit"
printf '  Notes:   generated by GitHub\n\n'
printf 'Type PUBLISH to create this GitHub release: '
read -r confirmation

if [[ "$confirmation" != "PUBLISH" ]]; then
  printf 'Release cancelled.\n'
  exit 1
fi

gh release create "$release_tag" \
  --target "$release_commit" \
  --title "$release_tag" \
  --generate-notes \
  --fail-on-no-commits \
  "${prerelease_args[@]}"

printf '\nRelease %s was published. The Release workflow is now running.\n' \
  "$release_tag"
